### ISSUE TITLE
Unexpected shear strain rate and driving stress result

### ISSUE THREAD

**Issue by shahinmg** [bryanvriel/iceutils#24]
Hi Bryan, 

iceutils is amazing and has helped my research out a lot. I have two questions regarding  the [compute_stress_strain](https://github.com/bryanvriel/iceutils/blob/master/iceutils/stress.py) function. 

1) I am confused about the shear strain rate output 'e_xy'. When using an its_live velocity sample, I did not see opposite signs when viewing the shear strain rate. I would imagine one side of the glacier being positive and the other being negative? I have provided an example figure below to illustrate this point. `e_xy_v2 = (0.5*((vx_gradient[0]/dy) + (vy_gradient[0]/dx)))` is the line that produces the 'edited' result.

![shear_strain_comparison](https://github.com/bryanvriel/iceutils/assets/46791000/66280219-3e55-4891-8377-583286ff2be1)

2) When I attempted to compute the driving stress, I get an output array with many holes in it. I am not sure if this is a result of the data inputs or not. I am curious as to your thought on this.
![driving_stress_fig](https://github.com/bryanvriel/iceutils/assets/46791000/b1930b14-dbdc-4c61-84b0-a012a99bb526)

I also have a repo [here](https://github.com/shahinmg/iceutils_scratch_space.git). This is just the code I used to make the above results. The python code lies here `iceutils_scratch_space/pys/shear_strain_rate_and_driving_stress.py`

Thanks for an amazing package!!

**Comment by bryanvriel** [comment]
Hi Michael, thanks for the message! It's been a while since we last talked at AGU. I'm happy to hear you've found some use for iceutils.

Regarding the strain rate, `e_xy` currently refers to the magnitude of the shear strain rate, which is why the values are only positive in your plot. However, it does make sense to return the signed version in addition to the magnitude. I'll create a PR with those changes and you can give that a test.

For the driving stress, I took a look at your data (thanks for putting everything in a repo). It turns out that the velocity rasters are stored as Int16, so when I compute the velocity magnitude (`mag = sqrt(vx**2 + vy**2)`), the values hit overflow. A simple way to address this is to cast the raster data into Float32 when you read them in, e.g.

```
vx = vx_r.read(1).astype(np.float32)
vy = vy_r.read(1).astype(np.float32)
```

That should fix most of the missing values within the glacier. There will still be a few missing values outside of the glacier due to the velocities having a value of 0. Hopefully that works for you!

**Comment by shahinmg** [comment]
Thank you so much for the quick and detailed response, Bryan! I just tested the strain branch and things look good!
![shear_strain_comparison_2](https://github.com/bryanvriel/iceutils/assets/46791000/d900f62d-5bac-4d3e-8144-056fbc369327)
I am assuming I messed up a sign somewhere, but the values are pretty similar when I checked with a quick profile.

Also the driving stress is now filled up.
![driving_stress_fig_2](https://github.com/bryanvriel/iceutils/assets/46791000/196330c5-c2b4-42b0-b9df-3594440f73b6)

Thanks again!!

**Comment by bryanvriel** [comment]
Glad it worked! Thanks for the feedback.
